---
title: "ggvis2"
author: "Russ Bjork"
date: "12/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A quick introduction to ggvis


```{r, echo=TRUE, eval=FALSE}
install.packages("ggvis")
```


## A first basic example
========================================================

```{r}
library(ggvis)
library(dplyr)
mtcars %>% ggvis(~wt, ~mpg) %>% layer_points()
mtcars %>% 
  ggvis(~wt, ~mpg) %>% 
  layer_points(fill = ~factor(cyl))
```

## Slide With Plot
========================================================

```{r, echo=FALSE}
plot(cars)
```

## Google Vis Example
========================================================

```{r gv, results='asis', cache=TRUE}
suppressPackageStartupMessages(library(googleVis))
M <- gvisMotionChart(Fruits,"Fruit","Year",option=list(width=600,height=400))
print(M,"chart")
```

## Chart output from googleVis
========================================================

<center> "gvis + ChartType" </center>